### ISSUE TITLE
UPX `unzipUpx` fails on linux platforms.

### ISSUE THREAD

**Issue by isXander** [JetBrains/package-search-gradle-plugins#22]
On linux, the error is as follows:

```
Caused by: org.gradle.api.InvalidUserCodeException: Cannot use tarTree() on a resource without a backing file.
        at org.gradle.api.internal.file.DefaultFileOperations.asFileProvider(DefaultFileOperations.java:227)
        at org.gradle.api.internal.file.DefaultFileOperations.tarTree(DefaultFileOperations.java:208)
        at org.gradle.api.internal.file.DefaultFileOperations.tarTree(DefaultFileOperations.java:75)
        at org.gradle.api.internal.project.DefaultProject.tarTree(DefaultProject.java:1014)
        at org.jetbrains.gradle.plugins.upx.UpxPlugin$apply$1$2.invoke(UpxPlugin.kt:77)
        at org.jetbrains.gradle.plugins.upx.UpxPlugin$apply$1$2.invoke(UpxPlugin.kt:19)
```

**Comment by sschuberth** [comment]
Just to note, this happens on task creation even if `unzipUpx` is not called:

```
* What went wrong:
Execution failed for task ':cli:tasks' (registered by plugin 'org.gradle.help-tasks').
> Could not create task ':cli:unzipUpx'.
   > Cannot use tarTree() on a resource without a backing file.
```

Tested with Gradle 9.6.1 and plugin version 1.6.0-RC.5.
